import type { Metadata } from "next";
import { Baloo_2, Nunito } from "next/font/google";

import CustomToasterComp from "@/components/custom/custom-toaster";
import { routing } from "@/i18n/routing";
import { getLangAttr } from "@/lib/utils";
import { LANGUAGES } from "@/shared/mocks/languages";
import { useLocale } from "next-intl";
import LocaleLayout from "./[locale]/layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "anfitrion",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

const baloo2 = Baloo_2({
  subsets: ["latin"],
  variable: "--font-baloo-2",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  const lang = useLocale();

  return (
    <html lang={getLangAttr(LANGUAGES, lang)}>
      <body className={`${nunito.variable} ${baloo2.variable}`}>
        <LocaleLayout>{children}</LocaleLayout>
        <CustomToasterComp />
      </body>
    </html>
  );
}
