import type { Metadata } from "next";
import { Nunito, Baloo_2 } from "next/font/google";

import "./globals.css";
import { routing } from "@/i18n/routing";
import { Toaster } from "@/components/ui/sonner";
import { NextIntlClientProvider, useLocale, useTranslations } from "next-intl";
import { LANGUAGES } from "@/shared/mocks/languages";
import { getLangAttr } from "@/lib/utils";
import CustomToasterComp from "@/components/custom/custom-toaster";
import { ThemeProvider } from "@/context/ThemeContext";
import { AuthProvider } from "@/context/AuthContext";
import LocaleLayout from "./[locale]/layout";

import * as z from "zod";
import { en, pt } from "zod/locales";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap",
});

const baloo2 = Baloo_2({
  subsets: ["latin"],
  variable: "--font-baloo-2",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  const lang = useLocale();

  return (
    <html lang={getLangAttr(LANGUAGES, lang)}>
      <body className={`${nunito.variable} ${baloo2.variable}`}>
        <LocaleLayout>{children}</LocaleLayout>
        <CustomToasterComp />
      </body>
    </html>
  );
}
